# Generated by Django 5.0.3 on 2024-05-31 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1200)),
                ('picture', models.URLField(default='https://placehold.co/200x250')),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('availability', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itinerary', models.JSONField()),
                ('included_meals', models.JSONField()),
                ('transportation_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('participants', models.CharField(max_length=200)),
                ('booking_qr', models.FileField(blank=True, null=True, upload_to='booking_qr/')),
                ('booking_pdf', models.FileField(blank=True, null=True, upload_to='booking_pdfs/')),
                ('tour_start_date', models.DateField()),
                ('tour_end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enjoy.tourpackage')),
            ],
        ),
    ]
