# Generated by Django 5.0.3 on 2024-06-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoy', '0003_alter_tourpackage_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_pdf', models.FileField(upload_to='booking_pdfs/')),
            ],
        ),
    ]
